package com.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.zolt.explain.gradle.GradleInspectionResult;
import com.zolt.explain.gradle.GradleStaticProjectInspector;
import com.zolt.explain.maven.MavenInspectionResult;
import com.zolt.explain.maven.MavenStaticProjectInspector;
import com.zolt.project.ProjectConfig;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class InspectionToProjectConfigTest {
    private static final Path FIXTURE_ROOT =
            ExplainEmitTestPaths.repositoryRoot().resolve("examples/migration-explain").normalize();

    @TempDir
    private Path tempDir;

    private final InspectionToProjectConfig mapper = new InspectionToProjectConfig();

    @Test
    void mavenSimpleMapsScopesToDependencySections() {
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-simple"));

        DraftZoltToml draft = mapper.fromMaven(result);
        ProjectConfig config = draft.config();

        assertEquals("21", config.project().java());
        assertEquals("maven-simple", config.project().name());
        assertTrue(config.project().main().isEmpty());
        assertEquals("33.4.8-jre", config.dependencies().get("com.google.guava:guava"));
        assertEquals("5.11.4", config.testDependencies().get("org.junit.jupiter:junit-jupiter"));
        assertFalse(config.dependencies().containsKey("org.junit.jupiter:junit-jupiter"));
    }

    @Test
    void mavenSimpleIsDeterministicAcrossRuns() {
        MavenStaticProjectInspector inspector = new MavenStaticProjectInspector();
        ProjectConfigRenderer renderer = new FakeRenderer();
        DraftZoltTomlRenderer draftRenderer = new DraftZoltTomlRenderer();

        String first = draftRenderer.render(mapper.fromMaven(inspector.inspect(FIXTURE_ROOT.resolve("maven-simple"))), renderer);
        String second = draftRenderer.render(mapper.fromMaven(inspector.inspect(FIXTURE_ROOT.resolve("maven-simple"))), renderer);

        assertEquals(first, second);
    }

    @Test
    void renderedDraftBeginsWithReviewBeforeUseNotice() {
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-simple"));
        String rendered = new DraftZoltTomlRenderer().render(mapper.fromMaven(result), new FakeRenderer());

        assertTrue(rendered.startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"));
        assertTrue(rendered.contains("# Review before use:"));
        assertTrue(rendered.contains("<<config>>"));
    }

    @Test
    void mavenMultiModuleSurfacesReactorAsComment() {
        MavenInspectionResult result =
                new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-multimodule"));

        DraftZoltToml draft = mapper.fromMaven(result);

        assertTrue(
                draft.notes().stream().anyMatch(note -> note.contains("Multi-module reactor detected")),
                () -> "expected reactor note in " + draft.notes());
        assertTrue(
                draft.notes().stream().anyMatch(note -> note.contains("Maven profiles were detected")),
                () -> "expected profile note in " + draft.notes());
    }

    @Test
    void gradleDraftUsesRootProjectNameGroupVersionAndMainClass() throws IOException {
        Files.writeString(tempDir.resolve("settings.gradle"), "rootProject.name = 'sales-report'\n");
        Files.writeString(tempDir.resolve("build.gradle"), """
                plugins { id 'java'\n    id 'application' }
                group = 'com.example'
                version = '0.3.1'
                application { mainClass = 'com.example.report.ReportApp' }
                dependencies {
                    implementation 'org.slf4j:slf4j-api:2.0.16'
                }
                """);

        GradleInspectionResult result = new GradleStaticProjectInspector().inspect(tempDir);
        DraftZoltToml draft = mapper.fromGradle(result);
        ProjectConfig config = draft.config();

        assertEquals("sales-report", config.project().name());
        assertEquals("com.example", config.project().group());
        assertEquals("0.3.1", config.project().version());
        assertEquals("com.example.report.ReportApp", config.project().main().orElseThrow());
        assertEquals("2.0.16", config.dependencies().get("org.slf4j:slf4j-api"));
        assertFalse(
                draft.notes().stream().anyMatch(note -> note.contains("could not read")),
                () -> "no cannot-read note expected when group/version are present: " + draft.notes());
    }

    @Test
    void gradleDraftFallsBackAndCommentsWhenGroupVersionAbsent() throws IOException {
        Files.writeString(tempDir.resolve("settings.gradle"), "rootProject.name = 'bare'\n");
        Files.writeString(tempDir.resolve("build.gradle"), """
                plugins { id 'java' }
                dependencies {
                    implementation 'com.example:lib:1.0'
                }
                """);

        GradleInspectionResult result = new GradleStaticProjectInspector().inspect(tempDir);
        DraftZoltToml draft = mapper.fromGradle(result);
        ProjectConfig config = draft.config();

        assertEquals("bare", config.project().name());
        assertEquals("com.example", config.project().group());
        assertEquals("0.1.0", config.project().version());
        assertTrue(config.project().main().isEmpty());
        assertTrue(
                draft.notes().stream().anyMatch(note ->
                        note.contains("group and version are placeholders")
                                && note.contains("could not read them")),
                () -> "expected the cannot-read fallback note: " + draft.notes());
    }

    private static final class FakeRenderer implements ProjectConfigRenderer {
        @Override
        public String render(ProjectConfig config) {
            return "<<config>>\n";
        }
    }
}
