package com.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.zolt.explain.maven.MavenInspectionResult;
import com.zolt.explain.maven.MavenStaticProjectInspector;
import com.zolt.project.ProjectConfig;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

final class InspectionToProjectConfigTest {
    private static final Path FIXTURE_ROOT =
            ExplainEmitTestPaths.repositoryRoot().resolve("examples/migration-explain").normalize();

    private final InspectionToProjectConfig mapper = new InspectionToProjectConfig();

    @Test
    void mavenSimpleMapsScopesToDependencySections() {
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-simple"));

        DraftZoltToml draft = mapper.fromMaven(result);
        ProjectConfig config = draft.config();

        assertEquals("21", config.project().java());
        assertEquals("maven-simple", config.project().name());
        assertTrue(config.project().main().isEmpty());
        assertEquals("33.4.8-jre", config.dependencies().get("com.google.guava:guava"));
        assertEquals("5.11.4", config.testDependencies().get("org.junit.jupiter:junit-jupiter"));
        assertFalse(config.dependencies().containsKey("org.junit.jupiter:junit-jupiter"));
    }

    @Test
    void mavenSimpleIsDeterministicAcrossRuns() {
        MavenStaticProjectInspector inspector = new MavenStaticProjectInspector();
        ProjectConfigRenderer renderer = new FakeRenderer();
        DraftZoltTomlRenderer draftRenderer = new DraftZoltTomlRenderer();

        String first = draftRenderer.render(mapper.fromMaven(inspector.inspect(FIXTURE_ROOT.resolve("maven-simple"))), renderer);
        String second = draftRenderer.render(mapper.fromMaven(inspector.inspect(FIXTURE_ROOT.resolve("maven-simple"))), renderer);

        assertEquals(first, second);
    }

    @Test
    void renderedDraftBeginsWithReviewBeforeUseNotice() {
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-simple"));
        String rendered = new DraftZoltTomlRenderer().render(mapper.fromMaven(result), new FakeRenderer());

        assertTrue(rendered.startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"));
        assertTrue(rendered.contains("# Review before use:"));
        assertTrue(rendered.contains("<<config>>"));
    }

    @Test
    void mavenMultiModuleSurfacesReactorAsComment() {
        MavenInspectionResult result =
                new MavenStaticProjectInspector().inspect(FIXTURE_ROOT.resolve("maven-multimodule"));

        DraftZoltToml draft = mapper.fromMaven(result);

        assertTrue(
                draft.notes().stream().anyMatch(note -> note.contains("Multi-module reactor detected")),
                () -> "expected reactor note in " + draft.notes());
        assertTrue(
                draft.notes().stream().anyMatch(note -> note.contains("Maven profiles were detected")),
                () -> "expected profile note in " + draft.notes());
    }

    private static final class FakeRenderer implements ProjectConfigRenderer {
        @Override
        public String render(ProjectConfig config) {
            return "<<config>>\n";
        }
    }
}
