package sh.zolt.explain.emit;

import java.util.List;
import java.util.Set;

/**
 * Renders a {@link DraftZoltToml} to a deterministic zolt.toml string: a fixed review-before-use
 * notice, the ambiguous-fact comment lines, then the mappable config serialized through the injected
 * {@link ProjectConfigRenderer}.
 *
 * <p>Output is stable across runs on the same input: no timestamps, no host paths, no ordering that
 * depends on hashing. Every comment line reads like Zolt's other errors — it states a fact and what
 * the adopter should do next.
 */
public final class DraftZoltTomlRenderer {
    private static final List<String> NOTICE = List.of(
            "# Draft zolt.toml generated by `zolt explain --emit-toml` from a static migration audit.",
            "# Review before use: Zolt did not run Maven or Gradle, so verify every version and scope",
            "# against your real build. No main class is set; add `main = \"...\"` if this is an"
                    + " application.",
            "# Ambiguous facts the audit could not map are listed as comments below; resolve them by"
                    + " hand.");

    public String render(DraftZoltToml draft, ProjectConfigRenderer renderer) {
        StringBuilder out = new StringBuilder();
        for (String line : NOTICE) {
            out.append(line).append('\n');
        }
        out.append(renderBody(draft, renderer));
        return out.toString();
    }

    /**
     * Renders the review-items comments and the config, without the standalone review-before-use
     * notice. Used for member documents inside a workspace bundle, whose notice lives once at the top.
     */
    public String renderBody(DraftZoltToml draft, ProjectConfigRenderer renderer) {
        StringBuilder out = new StringBuilder();
        if (!draft.notes().isEmpty()) {
            out.append('\n');
            out.append("# Review items:\n");
            for (String note : draft.notes()) {
                out.append("# ").append(note).append('\n');
            }
        }
        out.append('\n');
        out.append(renderConfig(draft, renderer));
        return out.toString();
    }

    private static final String COMPILER_PLATFORM_API_HOST_SUGGESTION =
            "# platformApi = \"host\"  # uncomment only if a post-target-Java platform API"
                    + " (e.g. an annotation processor) fails the strict --release build";

    private static String renderConfig(DraftZoltToml draft, ProjectConfigRenderer renderer) {
        String rendered = renderer.render(draft.config());
        if (!draft.commentedProjectKeys().isEmpty()) {
            rendered = commentProjectAssignments(rendered, Set.copyOf(draft.commentedProjectKeys()));
        }
        if (draft.suggestCompilerPlatformApiHost()) {
            rendered = withCompilerPlatformApiHostSuggestion(rendered);
        }
        return rendered;
    }

    /**
     * Adds the commented {@code # platformApi = "host"} suggestion as the last line of the
     * {@code [compiler]} section, synthesizing the section when the strict default meant the writer
     * emitted none.
     */
    private static String withCompilerPlatformApiHostSuggestion(String toml) {
        String[] lines = (toml.endsWith("\n") ? toml.substring(0, toml.length() - 1) : toml).split("\n", -1);
        int compilerHeader = -1;
        for (int i = 0; i < lines.length; i++) {
            if ("[compiler]".equals(lines[i].strip())) {
                compilerHeader = i;
                break;
            }
        }
        if (compilerHeader < 0) {
            StringBuilder appended = new StringBuilder(toml);
            if (appended.length() > 0 && appended.charAt(appended.length() - 1) != '\n') {
                appended.append('\n');
            }
            appended.append("\n[compiler]\n").append(COMPILER_PLATFORM_API_HOST_SUGGESTION).append('\n');
            return appended.toString();
        }
        int insertAt = lines.length;
        for (int i = compilerHeader + 1; i < lines.length; i++) {
            String stripped = lines[i].strip();
            if (stripped.startsWith("[") && stripped.endsWith("]")) {
                insertAt = i;
                break;
            }
        }
        // Insert before any trailing blank lines that separate this section from the next.
        while (insertAt > compilerHeader + 1 && lines[insertAt - 1].strip().isEmpty()) {
            insertAt--;
        }
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < lines.length; i++) {
            if (i == insertAt) {
                out.append(COMPILER_PLATFORM_API_HOST_SUGGESTION).append('\n');
            }
            out.append(lines[i]);
            if (i < lines.length - 1) {
                out.append('\n');
            }
        }
        if (insertAt == lines.length) {
            out.append('\n').append(COMPILER_PLATFORM_API_HOST_SUGGESTION);
        }
        out.append('\n');
        return out.toString();
    }

    private static String commentProjectAssignments(String toml, Set<String> keys) {
        StringBuilder out = new StringBuilder();
        boolean inProject = false;
        String[] lines = toml.split("\n", -1);
        for (int i = 0; i < lines.length; i++) {
            if (i > 0) {
                out.append('\n');
            }
            String line = lines[i];
            String stripped = line.strip();
            if ("[project]".equals(stripped)) {
                inProject = true;
            } else if (stripped.startsWith("[") && stripped.endsWith("]")) {
                inProject = false;
            }
            if (inProject && isCommentedAssignment(line, keys)) {
                out.append("# ");
            }
            out.append(line);
        }
        return out.toString();
    }

    private static boolean isCommentedAssignment(String line, Set<String> keys) {
        String stripped = line.stripLeading();
        if (stripped.startsWith("#")) {
            return false;
        }
        return keys.stream().anyMatch(key -> stripped.startsWith(key + " = "));
    }
}
