[project]
name = "zolt-workspace"
version = "0.1.0-SNAPSHOT"
group = "sh.zolt"
java = "21"

[repositories]
central = "https://repo.maven.apache.org/maven2"

[dependencies]
"sh.zolt:zolt-build" = { workspace = "modules/zolt-build" }
"sh.zolt:zolt-native-image" = { workspace = "modules/zolt-native-image" }
"sh.zolt:zolt-framework-api" = { workspace = "modules/zolt-framework-api" }
"sh.zolt:zolt-model" = { workspace = "modules/zolt-model" }
"sh.zolt:zolt-resolve" = { workspace = "modules/zolt-resolve" }
"sh.zolt:zolt-test-model" = { workspace = "modules/zolt-test-model" }
"sh.zolt:zolt-test-runtime" = { workspace = "modules/zolt-test-runtime" }
"sh.zolt:zolt-toml" = { workspace = "modules/zolt-toml" }

[test.dependencies]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[build]
source = "src/main/java"
test = "src/test/java"
output = "target/classes"
testOutput = "target/test-classes"
