package com.zolt.cli.insight;

import static com.zolt.cli.CliTestSupport.execute;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.zolt.cli.CliTestSupport.CommandResult;
import com.zolt.project.ProjectConfig;
import com.zolt.toml.ZoltTomlParser;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class ExplainCommandEmitTomlTest {
    private static final String MAVEN_SIMPLE_POM = """
            <project>
              <modelVersion>4.0.0</modelVersion>
              <groupId>dev.zolt.examples</groupId>
              <artifactId>maven-simple</artifactId>
              <version>1.0.0</version>
              <properties>
                <maven.compiler.release>21</maven.compiler.release>
              </properties>
              <dependencies>
                <dependency>
                  <groupId>com.google.guava</groupId>
                  <artifactId>guava</artifactId>
                  <version>33.4.8-jre</version>
                </dependency>
                <dependency>
                  <groupId>org.junit.jupiter</groupId>
                  <artifactId>junit-jupiter</artifactId>
                  <version>5.11.4</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
            </project>
            """;

    @TempDir
    private Path tempDir;

    @Test
    void emitsDraftTomlWithNoticeAndScopedDependencies() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, result.exitCode());
        assertEquals("", result.stderr());
        assertTrue(
                result.stdout().startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"),
                () -> "missing review notice in:\n" + result.stdout());
        assertTrue(result.stdout().contains("[project]"));
        assertTrue(result.stdout().contains("java = \"21\""));
        assertTrue(result.stdout().contains("[dependencies]"));
        assertTrue(result.stdout().contains("\"com.google.guava:guava\" = \"33.4.8-jre\""));
        assertTrue(result.stdout().contains("[test.dependencies]"));
        assertTrue(result.stdout().contains("\"org.junit.jupiter:junit-jupiter\" = \"5.11.4\""));
    }

    @Test
    void emittedDraftRoundTripsThroughZoltTomlParser() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        assertEquals(0, result.exitCode());

        ProjectConfig parsed = new ZoltTomlParser().parse(result.stdout());

        assertEquals("21", parsed.project().java());
        assertEquals("33.4.8-jre", parsed.dependencies().get("com.google.guava:guava"));
        assertEquals("5.11.4", parsed.testDependencies().get("org.junit.jupiter:junit-jupiter"));
        assertFalse(parsed.dependencies().containsKey("org.junit.jupiter:junit-jupiter"));
    }

    @Test
    void emitTomlIsByteForByteDeterministic() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult first = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");
        CommandResult second = execute("explain", "--emit-toml", "--cwd", tempDir.toString(), "--source", "maven");

        assertEquals(0, first.exitCode());
        assertEquals(first.stdout(), second.stdout());
    }

    @Test
    void emitTomlConflictsWithScorecard() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result =
                execute("explain", "--emit-toml", "--scorecard", "--cwd", tempDir.toString(), "--source", "maven");

        assertNotEquals(0, result.exitCode());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--scorecard"));
    }

    @Test
    void emitTomlConflictsWithBlockers() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), MAVEN_SIMPLE_POM);

        CommandResult result =
                execute("explain", "--emit-toml", "--blockers", "--cwd", tempDir.toString(), "--source", "maven");

        assertNotEquals(0, result.exitCode());
        assertTrue(result.stderr().contains("--emit-toml"));
        assertTrue(result.stderr().contains("--blockers"));
    }
}
