import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export async function writeSpringBootNativeWebProject(root: string): Promise<void> {
  await mkdir(join(root, "src/main/java/com/example/nativeweb"), { recursive: true });
  await mkdir(join(root, "src/main/resources"), { recursive: true });
  await writeFile(join(root, "zolt.toml"), [
    "[project]",
    'name = "spring-boot-native-web"',
    'version = "0.1.0"',
    'group = "com.example"',
    'java = "21"',
    'main = "com.example.nativeweb.NativeWebApplication"',
    "",
    "[repositories]",
    'central = "https://repo.maven.apache.org/maven2"',
    "",
    "[platforms]",
    '"org.springframework.boot:spring-boot-dependencies" = "3.3.6"',
    "",
    "[dependencies]",
    '"org.springframework.boot:spring-boot-starter-actuator" = {}',
    '"org.springframework.boot:spring-boot-starter-jdbc" = {}',
    '"org.springframework.boot:spring-boot-starter-web" = {}',
    "",
    "[runtime.dependencies]",
    '"com.h2database:h2" = {}',
    "",
    "[framework.springBoot.native]",
    "enabled = true",
    "",
    "[native]",
    'imageName = "spring-boot-native-web"',
    'output = "target/native"',
    "args = [",
    '  "-H:+UnlockExperimentalVMOptions",',
    '  "--no-fallback"',
    "]",
    "",
    "[resources]",
    'main = ["src/main/resources"]',
    "",
  ].join("\n"), "utf8");
  await writeFile(join(root, "src/main/resources/application.properties"), [
    "management.endpoints.web.exposure.include=health",
    "server.address=127.0.0.1",
    "spring.datasource.url=jdbc:h2:mem:zolt_native_data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL",
    "spring.datasource.type=org.springframework.jdbc.datasource.SimpleDriverDataSource",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.datasource.username=sa",
    "spring.datasource.password=",
    "",
  ].join("\n"), "utf8");
  await writeFile(join(root, "src/main/java/com/example/nativeweb/NativeWebApplication.java"), [
    "package com.example.nativeweb;",
    "",
    "import java.util.Map;",
    "import java.util.concurrent.atomic.AtomicLong;",
    "import org.springframework.boot.SpringApplication;",
    "import org.springframework.boot.autoconfigure.SpringBootApplication;",
    "import org.springframework.http.HttpStatus;",
    "import org.springframework.jdbc.core.simple.JdbcClient;",
    "import org.springframework.web.bind.annotation.GetMapping;",
    "import org.springframework.web.bind.annotation.PostMapping;",
    "import org.springframework.web.bind.annotation.PathVariable;",
    "import org.springframework.web.bind.annotation.RequestBody;",
    "import org.springframework.web.bind.annotation.RestController;",
    "import org.springframework.web.server.ResponseStatusException;",
    "",
    "@SpringBootApplication",
    "@RestController",
    "public class NativeWebApplication {",
    "    private final JdbcClient jdbc;",
    "    private final AtomicLong nextId = new AtomicLong(1);",
    "",
    "    NativeWebApplication(JdbcClient jdbc) {",
    "        this.jdbc = jdbc;",
    '        jdbc.sql("create table if not exists notes (id bigint primary key, text varchar(255) not null)").update();',
    "    }",
    "",
    "    public static void main(String[] args) { SpringApplication.run(NativeWebApplication.class, args); }",
    "",
    "    @GetMapping(\"/hello\")",
    "    Map<String, String> hello() { return Map.of(\"message\", \"hello from native Spring Boot\"); }",
    "",
    "    @PostMapping(\"/echo\")",
    "    EchoRequest echo(@RequestBody EchoRequest request) {",
    "        if (request.message() == null || request.message().isBlank()) {",
    '            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "message must not be blank");',
    "        }",
    "        return new EchoRequest(request.message().trim());",
    "    }",
    "",
    "    @PostMapping(\"/data-notes\")",
    "    Note createNote(@RequestBody NoteInput input) {",
    "        if (input.text() == null || input.text().isBlank()) {",
    '            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "text must not be blank");',
    "        }",
    "        long id = nextId.getAndIncrement();",
    '        jdbc.sql("insert into notes (id, text) values (:id, :text)")',
    '                .param("id", id).param("text", input.text().trim()).update();',
    "        return new Note(id, input.text().trim());",
    "    }",
    "",
    "    @GetMapping(\"/data-notes/{id}\")",
    "    Note findNote(@PathVariable(\"id\") long id) {",
    '        return jdbc.sql("select id, text from notes where id = :id").param("id", id)',
    '                .query((rs, row) -> new Note(rs.getLong("id"), rs.getString("text")))',
    '                .optional().orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "note not found"));',
    "    }",
    "",
    "    public record EchoRequest(String message) {}",
    "    public record NoteInput(String text) {}",
    "    public record Note(long id, String text) {}",
    "}",
    "",
  ].join("\n"), "utf8");
}
