package sh.zolt.sbom;

import java.util.Comparator;
import java.util.List;

/**
 * Writes a deterministic THIRD_PARTY notices file: each in-scope dependency (sorted by coordinate)
 * followed by its licenses as {@code name (url)}. Full license texts are intentionally not bundled in
 * v1 (offline guarantee + maintenance cost).
 */
public final class LicenseNoticesWriter {
    public String write(List<SbomComponent> components, LicenseIndex index) {
        StringBuilder text = new StringBuilder();
        text.append("THIRD-PARTY SOFTWARE NOTICES\n");
        text.append("Generated by Zolt. Lists third-party dependencies and their declared licenses.\n\n");

        List<SbomComponent> sorted = components.stream()
                .sorted(Comparator.comparing(component ->
                        component.group() + ":" + component.name() + ":" + component.version()))
                .toList();
        for (int index2 = 0; index2 < sorted.size(); index2++) {
            SbomComponent component = sorted.get(index2);
            String coordinate = component.group() + ":" + component.name() + ":" + component.version();
            text.append(coordinate).append('\n');
            List<SbomLicense> licenses = index.forCoordinate(coordinate);
            if (licenses.isEmpty()) {
                licenses = List.of(SbomLicense.unknown());
            }
            for (SbomLicense license : licenses) {
                text.append("  ").append(noticeLine(license)).append('\n');
            }
            if (index2 + 1 < sorted.size()) {
                text.append('\n');
            }
        }
        return text.toString();
    }

    private static String noticeLine(SbomLicense license) {
        return switch (license.status()) {
            case SPDX -> license.spdxId().orElse("UNKNOWN");
            case UNMAPPED -> license.url()
                    .map(url -> license.displayName() + " (" + url + ")")
                    .orElseGet(license::displayName);
            case UNKNOWN -> "UNKNOWN";
        };
    }
}
