package sh.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.project.BuildSettings;
import sh.zolt.project.NativeSettings;
import sh.zolt.project.ProjectConfig;
import sh.zolt.project.ProjectConfigs;
import sh.zolt.project.ProjectMetadata;
import sh.zolt.workspace.WorkspaceConfig;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

final class DraftWorkspaceRendererTest {
    @Test
    void renderBundleIncludesReviewItemsHeadersAndMemberBodies() {
        String rendered = new DraftWorkspaceRenderer().render(
                workspaceDraft(),
                new FakeWorkspaceRenderer(),
                new FakeProjectRenderer());

        assertTrue(rendered.startsWith("# Draft Zolt workspace generated by `zolt explain --emit-toml`"),
                () -> rendered);
        assertTrue(rendered.contains("# Review items:\n"
                + "# Root aggregator declares dependencies that must move into members.\n"), () -> rendered);
        assertTrue(rendered.contains("# --- zolt.toml (workspace root) ---\n"
                + "[workspace]\n"
                + "name = \"shop\"\n"
                + "members = [\"app\", \"lib\"]\n"), () -> rendered);
        assertTrue(rendered.contains("# --- app/zolt.toml ---\n"
                + "# Review items:\n"
                + "# app has a classifier dependency to review.\n"
                + "\n"
                + "[project]\n"
                + "name = \"app\"\n"), () -> rendered);
        assertTrue(rendered.contains("# --- lib/zolt.toml ---\n"
                + "[project]\n"
                + "name = \"lib\"\n"), () -> rendered);
        assertTrue(rendered.endsWith("\n"), () -> rendered);
    }

    @Test
    void renderDocumentsSplitsRootAndMembersWithTrailingNewlines() {
        List<DraftZoltTomlDocument> documents = new DraftWorkspaceRenderer().renderDocuments(
                workspaceDraft(),
                new FakeWorkspaceRenderer(),
                new FakeProjectRenderer());

        assertEquals(List.of("zolt.toml", "app/zolt.toml", "lib/zolt.toml"),
                documents.stream().map(DraftZoltTomlDocument::relativePath).toList());
        assertTrue(documents.get(0).contents().contains(
                "# Draft Zolt workspace generated by `zolt explain --emit-toml`"), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().contains("# Review items:\n"
                + "# Root aggregator declares dependencies that must move into members.\n"), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().contains("[workspace]\n"), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().endsWith("\n"), documents.get(0)::contents);

        assertTrue(documents.get(1).contents().startsWith("# Review items:\n"
                + "# app has a classifier dependency to review.\n"
                + "\n"
                + "[project]\n"), documents.get(1)::contents);
        assertTrue(documents.get(1).contents().endsWith("\n"), documents.get(1)::contents);
        assertTrue(documents.get(2).contents().startsWith("[project]\n"), documents.get(2)::contents);
        assertTrue(documents.get(2).contents().endsWith("\n"), documents.get(2)::contents);
    }

    @Test
    void draftDocumentsRejectBlankPathAndNullContents() {
        IllegalArgumentException blankPath = assertThrows(
                IllegalArgumentException.class,
                () -> new DraftZoltTomlDocument(" ", ""));
        assertEquals("A draft zolt.toml document must have a non-blank relative path.", blankPath.getMessage());

        IllegalArgumentException nullContents = assertThrows(
                IllegalArgumentException.class,
                () -> new DraftZoltTomlDocument("app/zolt.toml", null));
        assertEquals("A draft zolt.toml document must have contents.", nullContents.getMessage());
    }

    @Test
    void workspaceMembersRejectBlankPath() {
        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> new DraftWorkspace.Member("\t", draft("blank")));

        assertEquals("A workspace member must have a non-blank relative path.", exception.getMessage());
    }

    private static DraftWorkspace workspaceDraft() {
        return new DraftWorkspace(
                new WorkspaceConfig("shop", List.of("app", "lib"), List.of("app"), Map.of(), Map.of()),
                List.of(
                        new DraftWorkspace.Member(
                                "app",
                                new DraftZoltToml(
                                        project("app"),
                                        List.of("app has a classifier dependency to review."))),
                        new DraftWorkspace.Member("lib", draft("lib"))),
                List.of("Root aggregator declares dependencies that must move into members."));
    }

    private static DraftZoltToml draft(String name) {
        return new DraftZoltToml(project(name), List.of());
    }

    private static ProjectConfig project(String name) {
        return ProjectConfigs.withDirectDependencies(
                new ProjectMetadata(name, "1.0.0", "com.example", "21", Optional.empty()),
                ProjectConfig.defaultRepositories(),
                Map.of(),
                Map.of(),
                BuildSettings.defaults(),
                NativeSettings.defaults());
    }

    private static final class FakeProjectRenderer implements ProjectConfigRenderer {
        @Override
        public String render(ProjectConfig config) {
            return """
                    [project]
                    name = "%s"
                    version = "%s"
                    """.formatted(config.project().name(), config.project().version());
        }
    }

    private static final class FakeWorkspaceRenderer implements WorkspaceConfigRenderer {
        @Override
        public String render(WorkspaceConfig config) {
            String members = config.members().stream()
                    .map(member -> "\"" + member + "\"")
                    .collect(Collectors.joining(", "));
            return """
                    [workspace]
                    name = "%s"
                    members = [%s]
                    """.formatted(config.name(), members);
        }
    }
}
