package sh.zolt.explain.emit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.explain.gradle.GradleInspectionResult;
import sh.zolt.explain.gradle.GradleStaticProjectInspector;
import sh.zolt.explain.maven.MavenInspectionResult;
import sh.zolt.explain.maven.MavenStaticProjectInspector;
import sh.zolt.project.ProjectConfig;
import sh.zolt.workspace.WorkspaceConfig;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

final class EmitRendererTest {
    @TempDir
    private Path tempDir;

    @Test
    void mavenSingleProjectCanRenderTextAndDocument() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.acme</groupId>
                  <artifactId>demo</artifactId>
                  <version>1.0.0</version>
                </project>
                """);
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(tempDir);
        EmitRenderer renderer = renderer();

        String text = renderer.renderMaven(result);
        List<DraftZoltTomlDocument> documents = renderer.renderMavenDocuments(result);

        assertTrue(text.startsWith("# Draft zolt.toml generated by `zolt explain --emit-toml`"), () -> text);
        assertTrue(text.contains("name = \"demo\""), () -> text);
        assertEquals(1, documents.size());
        assertEquals("zolt.toml", documents.get(0).relativePath());
        assertTrue(documents.get(0).contents().contains("name = \"demo\""), documents.get(0)::contents);
        assertTrue(documents.get(0).contents().endsWith("\n"), documents.get(0)::contents);
    }

    @Test
    void mavenReactorCanRenderWorkspaceTextAndSplitDocuments() throws IOException {
        writeMavenReactor();
        MavenInspectionResult result = new MavenStaticProjectInspector().inspect(tempDir);
        EmitRenderer renderer = renderer();

        String text = renderer.renderMaven(result);
        List<DraftZoltTomlDocument> documents = renderer.renderMavenDocuments(result);

        assertTrue(text.contains("# --- zolt.toml (workspace root) ---\n[workspace]\nname = \"demo-parent\"\n"),
                () -> text);
        assertTrue(text.contains("# --- service/zolt.toml ---\n"), () -> text);
        assertTrue(text.contains("[project]\nname = \"service\"\n"), () -> text);
        assertEquals(List.of("zolt.toml", "service/zolt.toml"),
                documents.stream().map(DraftZoltTomlDocument::relativePath).toList());
        assertTrue(documents.get(0).contents().contains("[workspace]\nname = \"demo-parent\"\n"),
                documents.get(0)::contents);
        assertTrue(documents.get(1).contents().contains("[project]\nname = \"service\"\n"),
                documents.get(1)::contents);
    }

    @Test
    void gradleSingleProjectCanRenderTextAndDocument() throws IOException {
        Files.writeString(tempDir.resolve("settings.gradle"), "rootProject.name = 'gradle-demo'\n");
        Files.writeString(tempDir.resolve("build.gradle"), """
                plugins { id 'java' }
                group = 'com.acme'
                version = '1.2.3'
                """);
        GradleInspectionResult result = new GradleStaticProjectInspector().inspect(tempDir);
        EmitRenderer renderer = renderer();

        String text = renderer.renderGradle(result);
        List<DraftZoltTomlDocument> documents = renderer.renderGradleDocuments(result);

        assertTrue(text.contains("name = \"gradle-demo\""), () -> text);
        assertEquals(1, documents.size());
        assertEquals("zolt.toml", documents.get(0).relativePath());
        assertTrue(documents.get(0).contents().contains("version = \"1.2.3\""), documents.get(0)::contents);
    }

    private void writeMavenReactor() throws IOException {
        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <groupId>com.acme</groupId>
                  <artifactId>demo-parent</artifactId>
                  <version>1.0.0</version>
                  <packaging>pom</packaging>
                  <modules>
                    <module>service</module>
                  </modules>
                </project>
                """);
        Path service = tempDir.resolve("service");
        Files.createDirectories(service);
        Files.writeString(service.resolve("pom.xml"), """
                <project>
                  <modelVersion>4.0.0</modelVersion>
                  <parent>
                    <groupId>com.acme</groupId>
                    <artifactId>demo-parent</artifactId>
                    <version>1.0.0</version>
                  </parent>
                  <artifactId>service</artifactId>
                </project>
                """);
    }

    private static EmitRenderer renderer() {
        return new EmitRenderer(
                new InspectionToProjectConfig(),
                new DraftZoltTomlRenderer(),
                new DraftWorkspaceRenderer(),
                new FakeProjectRenderer(),
                new FakeWorkspaceRenderer());
    }

    private static final class FakeProjectRenderer implements ProjectConfigRenderer {
        @Override
        public String render(ProjectConfig config) {
            return """
                    [project]
                    name = "%s"
                    version = "%s"
                    group = "%s"
                    java = "%s"
                    """.formatted(
                    config.project().name(),
                    config.project().version(),
                    config.project().group(),
                    config.project().java());
        }
    }

    private static final class FakeWorkspaceRenderer implements WorkspaceConfigRenderer {
        @Override
        public String render(WorkspaceConfig config) {
            String members = config.members().stream()
                    .map(member -> "\"" + member + "\"")
                    .collect(Collectors.joining(", "));
            return """
                    [workspace]
                    name = "%s"
                    members = [%s]
                    """.formatted(config.name(), members);
        }
    }
}
