package com.zolt.explain.emit;

import java.util.List;

/**
 * Renders a {@link DraftZoltToml} to a deterministic zolt.toml string: a fixed review-before-use
 * notice, the ambiguous-fact comment lines, then the mappable config serialized through the injected
 * {@link ProjectConfigRenderer}.
 *
 * <p>Output is stable across runs on the same input: no timestamps, no host paths, no ordering that
 * depends on hashing. Every comment line reads like Zolt's other errors — it states a fact and what
 * the adopter should do next.
 */
public final class DraftZoltTomlRenderer {
    private static final List<String> NOTICE = List.of(
            "# Draft zolt.toml generated by `zolt explain --emit-toml` from a static migration audit.",
            "# Review before use: Zolt did not run Maven or Gradle, so verify every version and scope",
            "# against your real build. No main class is set; add `main = \"...\"` if this is an"
                    + " application.",
            "# Ambiguous facts the audit could not map are listed as comments below; resolve them by"
                    + " hand.");

    public String render(DraftZoltToml draft, ProjectConfigRenderer renderer) {
        StringBuilder out = new StringBuilder();
        for (String line : NOTICE) {
            out.append(line).append('\n');
        }
        if (!draft.notes().isEmpty()) {
            out.append('\n');
            out.append("# Review items:\n");
            for (String note : draft.notes()) {
                out.append("# ").append(note).append('\n');
            }
        }
        out.append('\n');
        out.append(renderer.render(draft.config()));
        return out.toString();
    }
}
