package com.zolt.explain.emit;

/**
 * Renders a {@link DraftWorkspace} to a deterministic multi-document zolt.toml bundle: a
 * review-before-use notice, workspace-level review comments, the root {@code [workspace]} document,
 * then one member document per module. Every document carries a {@code # --- <path>/zolt.toml ---}
 * header so the adopter can see exactly which file each block becomes.
 *
 * <p>Output is stable across runs on the same input: no timestamps, no host paths, no hashing-order
 * dependence. Members are rendered in the order the mapper lists them (sorted by path).
 */
public final class DraftWorkspaceRenderer {
    private static final String NOTICE =
            "# Draft Zolt workspace generated by `zolt explain --emit-toml` from a static migration"
                    + " audit.\n"
                    + "# This build is multi-module, so it maps to a Zolt workspace: a root [workspace]\n"
                    + "# document plus one member zolt.toml per module. Split each `# --- <path> ---`\n"
                    + "# section into its own file at that path.\n"
                    + "# Review before use: Zolt did not run Maven or Gradle, so verify every version,\n"
                    + "# scope, and inter-module edge against your real build.";

    private final DraftZoltTomlRenderer memberRenderer;

    public DraftWorkspaceRenderer() {
        this(new DraftZoltTomlRenderer());
    }

    public DraftWorkspaceRenderer(DraftZoltTomlRenderer memberRenderer) {
        this.memberRenderer = memberRenderer;
    }

    public String render(
            DraftWorkspace draft,
            WorkspaceConfigRenderer workspaceRenderer,
            ProjectConfigRenderer configRenderer) {
        StringBuilder out = new StringBuilder();
        out.append(NOTICE).append('\n');
        if (!draft.notes().isEmpty()) {
            out.append("\n# Review items:\n");
            for (String note : draft.notes()) {
                out.append("# ").append(note).append('\n');
            }
        }
        out.append('\n');
        out.append("# --- zolt.toml (workspace root) ---\n");
        out.append(workspaceRenderer.render(draft.workspace()));
        for (DraftWorkspace.Member member : draft.members()) {
            out.append('\n');
            out.append("# --- ").append(member.path()).append("/zolt.toml ---\n");
            out.append(memberRenderer.renderBody(member.draft(), configRenderer).stripLeading());
            out.append('\n');
        }
        return out.toString();
    }
}
