[project]
name = "zolt-quality"
version = "0.1.0-SNAPSHOT"
group = "sh.zolt"
java = "21"

[repositories]
central = "https://repo.maven.apache.org/maven2"

[dependencies]
"sh.zolt:zolt-build" = { workspace = "modules/zolt-build" }
"sh.zolt:zolt-model" = { workspace = "modules/zolt-model" }
"sh.zolt:zolt-policy" = { workspace = "modules/zolt-policy" }
"sh.zolt:zolt-publish" = { workspace = "modules/zolt-publish" }
"sh.zolt:zolt-repository" = { workspace = "modules/zolt-repository" }
"sh.zolt:zolt-resolve" = { workspace = "modules/zolt-resolve" }
"sh.zolt:zolt-sbom" = { workspace = "modules/zolt-sbom" }
"sh.zolt:zolt-toml" = { workspace = "modules/zolt-toml" }
"sh.zolt:zolt-workspace" = { workspace = "modules/zolt-workspace" }

[test.dependencies]
"org.junit.platform:junit-platform-console-standalone" = "1.11.4"

[build]
source = "src/main/java"
test = "src/test/java"
output = "target/classes"
testOutput = "target/test-classes"
