spring.application.name=spring-boot-enterprise-canary
spring.main.banner-mode=off
management.endpoints.web.exposure.include=health,info
enterprise.canary.version=@projectVersion@
enterprise.canary.platform=@enterprisePlatformVersion@
enterprise.canary.greeting=Hello from Zolt enterprise canary
