[project]
name = "quarkus-http"
version = "0.1.0"
group = "com.example"
java = "21"

[repositories]
central = "https://repo.maven.apache.org/maven2"

[platforms]
"io.quarkus.platform:quarkus-bom" = "3.33.2"

[dependencies]
"io.quarkus:quarkus-rest" = {}

[test.dependencies]
"org.junit.jupiter:junit-jupiter" = {}

[build]
source = "src/main/java"
test = "src/test/java"
output = "target/classes"
testOutput = "target/test-classes"

[framework.quarkus]
enabled = true
package = "fast-jar"
