[project]
name = "spring-boot-webmvc"
version = "0.1.0"
group = "com.example"
java = "21"
main = "com.example.springboot.DemoApplication"

[repositories]
central = "https://repo.maven.apache.org/maven2"

[platforms]
"org.springframework.boot:spring-boot-dependencies" = "4.0.6"

[dependencies]
"org.springframework.boot:spring-boot-starter-webmvc" = {}

[test.dependencies]
"org.springframework.boot:spring-boot-starter-test" = {}

[build]
source = "src/main/java"
test = "src/test/java"
output = "target/classes"
testOutput = "target/test-classes"

[build.metadata]
buildInfo = true
git = true
reproducible = true

[resources]
main = ["src/main/resources", "target/generated/resources"]
test = ["src/test/resources"]
