package sh.zolt.cli.resolve;

import sh.zolt.cli.CliTestRepository;

import static sh.zolt.cli.CliTestSupport.execute;
import static sh.zolt.cli.CliTestSupport.memberConfig;
import static sh.zolt.cli.resolve.ResolveCommandTestSupport.writeProjectConfig;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import sh.zolt.cli.CliTestSupport.CommandResult;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Covers  (resolve half): a resolve that near-empties an emit draft warns and drops the
 * unqualified {@code Next: zolt build} hand-off, while a fully-resolved draft keeps today's green
 * summary and hand-off unchanged.
 */
final class ResolveDraftWarningTest {
    @TempDir
    private Path tempDir;

    @Test
    void fullyResolvedDraftKeepsGreenSummaryAndBuildHandoff() throws IOException {
        try (CliTestRepository repository = CliTestRepository.start()) {
            repository.addArtifact("com.example", "app", "1.0.0", """
                    <project>
                      <groupId>com.example</groupId>
                      <artifactId>app</artifactId>
                      <version>1.0.0</version>
                    </project>
                    """);
            Path projectDir = tempDir.resolve("resolved-draft");
            writeProjectConfig(projectDir, repository.baseUri().toString(), Map.of("com.example:app", "1.0.0"));

            CommandResult result = execute(
                    "--color=never",
                    "resolve",
                    "--cwd", projectDir.toString(),
                    "--cache-root", tempDir.resolve("cache").toString());

            assertEquals(0, result.exitCode());
            assertTrue(result.stdout().contains("✔ Resolved 1 packages"));
            assertTrue(result.stdout().contains("Next: zolt build"));
            assertFalse(result.stdout().contains("warning:"));
        }
    }

    @Test
    void reviewItemDraftWarnsAndSuppressesBuildHandoff() throws IOException {
        Path projectDir = tempDir.resolve("review-item-draft");
        Files.createDirectories(projectDir);
        Files.writeString(projectDir.resolve("zolt.toml"), """
                # Draft zolt.toml generated by `zolt explain --emit-toml` from a static migration audit.
                # Review before use.
                %s
                # Review items:
                # Dependency `org.springframework.boot:spring-boot-starter-web` has no static version.

                [repositories]
                central = "https://repo.maven.apache.org/maven2"

                [dependencies]

                [test.dependencies]
                """.formatted(memberConfig("review-item-draft")));
        Path sources = projectDir.resolve("src/main/java/com/example");
        Files.createDirectories(sources);
        Files.writeString(sources.resolve("Main.java"), """
                package com.example;
                import org.springframework.boot.SpringApplication;
                public final class Main {}
                """);

        CommandResult result = execute(
                "--color=never",
                "resolve",
                "--cwd", projectDir.toString(),
                "--cache-root", tempDir.resolve("cache").toString());

        assertEquals(0, result.exitCode());
        assertTrue(result.stdout().contains("✔ Resolved 0 packages"));
        assertTrue(result.stdout().contains("warning:"));
        assertTrue(result.stdout().contains("were not resolved"));
        assertFalse(result.stdout().contains("Next: zolt build"));
    }

    @Test
    void emptyGraphWithDeclaredSourcesWarnsWithoutReviewMarkers() throws IOException {
        Path projectDir = tempDir.resolve("empty-graph-with-sources");
        writeProjectConfig(projectDir, Map.of());
        Path sources = projectDir.resolve("src/main/java/com/example");
        Files.createDirectories(sources);
        Files.writeString(sources.resolve("Main.java"), """
                package com.example;
                public final class Main {}
                """);

        CommandResult result = execute(
                "--color=never",
                "resolve",
                "--cwd", projectDir.toString(),
                "--cache-root", tempDir.resolve("cache").toString());

        assertEquals(0, result.exitCode());
        assertTrue(result.stdout().contains("✔ Resolved 0 packages"));
        assertTrue(result.stdout().contains("warning:"));
        assertFalse(result.stdout().contains("Next: zolt build"));
    }

    @Test
    void emptyDependencyFreeProjectWithoutSourcesKeepsGreenHandoff() throws IOException {
        Path projectDir = tempDir.resolve("empty-no-sources");
        writeProjectConfig(projectDir, Map.of());

        CommandResult result = execute(
                "--color=never",
                "resolve",
                "--cwd", projectDir.toString(),
                "--cache-root", tempDir.resolve("cache").toString());

        assertEquals(0, result.exitCode());
        assertTrue(result.stdout().contains("✔ Resolved 0 packages"));
        assertTrue(result.stdout().contains("Next: zolt build"));
        assertFalse(result.stdout().contains("warning:"));
    }
}
