package sh.zolt.sbom;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import sh.zolt.dependency.DependencyScope;
import sh.zolt.lockfile.ZoltLockfile;

final class LicenseReportTest extends SbomTestSupport {
    private final LockSbomAssembler assembler = new LockSbomAssembler();
    private final LicenseReportBuilder builder = new LicenseReportBuilder();

    private List<SbomComponent> components() {
        ZoltLockfile lockfile = lockfile(
                Optional.of("sha256:demo-lock-fingerprint"),
                maven("org.example", "lib-a", "1.0.0", DependencyScope.COMPILE, true, SHA_A, List.of()),
                maven("org.example", "lib-b", "2.0.0", DependencyScope.COMPILE, true, SHA_B, List.of()),
                maven("org.example", "lib-c", "3.0.0", DependencyScope.COMPILE, true, SHA_C, List.of()));
        return assembler.assemble(
                config(), lockfile, SbomScopeSelection.requiredOnly(), Optional.empty(), TOOL_VERSION, index())
                .components();
    }

    private LicenseIndex index() {
        return new LicenseIndex(
                Map.of(
                        "org.example:lib-a:1.0.0", List.of(SbomLicense.spdx("Apache-2.0")),
                        "org.example:lib-b:2.0.0",
                        List.of(SbomLicense.unmapped(Optional.of("Weird License"), Optional.of("https://example.com/l"))),
                        "org.example:lib-c:3.0.0", List.of(SbomLicense.unknown())),
                List.of("org.example:lib-c:3.0.0"));
    }

    @Test
    void groupsByLicenseLabelWithStatuses() {
        LicenseReport report = builder.build(components(), index());

        assertEquals(List.of("Apache-2.0", "UNKNOWN", "Weird License"),
                report.groups().stream().map(LicenseGroup::label).toList());
        assertEquals(List.of(SbomLicenseStatus.SPDX, SbomLicenseStatus.UNKNOWN, SbomLicenseStatus.UNMAPPED),
                report.groups().stream().map(LicenseGroup::status).toList());
    }

    @Test
    void writesGroupedTextReportWithActionableNotes() {
        String text = new LicenseReportTextWriter().write(builder.build(components(), index()));

        assertEquals("""
                Apache-2.0 (1)
                  org.example:lib-a:1.0.0

                UNKNOWN (1)
                  org.example:lib-c:3.0.0
                  note: no license found in the cached POM chain; run `zolt resolve` to cache POMs, then re-run.

                Weird License (https://example.com/l) (1)
                  org.example:lib-b:2.0.0
                  note: unrecognized license spelling; kept raw. Verify the license manually.
                """, text);
    }

    @Test
    void writesGoldenLicensesJson() {
        String json = new LicenseReportJsonWriter().write(builder.build(components(), index()));

        assertEquals("""
                {
                  "schemaVersion": 1,
                  "command": "licenses",
                  "groups": [
                    {
                      "license": "Apache-2.0",
                      "status": "spdx",
                      "url": null,
                      "components": [
                        {
                          "coordinate": "org.example:lib-a:1.0.0",
                          "purl": "pkg:maven/org.example/lib-a@1.0.0?type=jar"
                        }
                      ]
                    },
                    {
                      "license": "UNKNOWN",
                      "status": "unknown",
                      "url": null,
                      "components": [
                        {
                          "coordinate": "org.example:lib-c:3.0.0",
                          "purl": "pkg:maven/org.example/lib-c@3.0.0?type=jar"
                        }
                      ]
                    },
                    {
                      "license": "Weird License",
                      "status": "unmapped",
                      "url": "https://example.com/l",
                      "components": [
                        {
                          "coordinate": "org.example:lib-b:2.0.0",
                          "purl": "pkg:maven/org.example/lib-b@2.0.0?type=jar"
                        }
                      ]
                    }
                  ]
                }
                """, json);
    }

    @Test
    void writesDeterministicThirdPartyNotices() {
        String notices = new LicenseNoticesWriter().write(components(), index());

        assertEquals("""
                THIRD-PARTY SOFTWARE NOTICES
                Generated by Zolt. Lists third-party dependencies and their declared licenses.

                org.example:lib-a:1.0.0
                  Apache-2.0

                org.example:lib-b:2.0.0
                  Weird License (https://example.com/l)

                org.example:lib-c:3.0.0
                  UNKNOWN
                """, notices);
    }
}
